#!/bin/bash

if screen -list | grep -q "deliveryTrayAgent"; then
  screen -ls | grep -E "deliveryTrayAgent" | cut -d. -f1 | awk '{print }' | xargs kill 2> /dev/null
  ps -eo pid,command | grep conveyorbelt | grep -v grep | awk '{system("sudo kill -9 " $1)}'
    echo "Chariot Delivery Tray agent stopped."
else
  echo "Chariot Delivery Tray agent isn't running."
fi
