#!/bin/bash

if screen -list | grep -q "threeDPrinterAgent"; then
  screen -ls | grep -E "threeDPrinterAgent" | cut -d. -f1 | awk '{print }' | xargs kill 2> /dev/null
  # ps -eo pid,command | grep threeDPrinterAgent | grep -v grep | awk '{system("sudo kill -9 " $1)}'
    echo "Chariot three d printer  agent stopped."
else
  echo "Chariot three d printer  agent isn't running."
fi
