#!/bin/bash

if screen -list | grep -q "chargingStationAgent"; then
  screen -ls | grep -E "chargingStationAgent" | cut -d. -f1 | awk '{print }' | xargs kill 2> /dev/null
  ps -eo pid,command | grep chargingStationAgent | grep -v grep | awk '{system("sudo kill -9 " $1)}'
    echo "Chariot Charging Station agent stopped."
else
  echo "Chariot Charging Station agent isn't running."
fi
