#!/bin/bash

if screen -list | grep -q "infraredSensorAgent"; then
  screen -ls | grep -E "infraredSensorAgent" | cut -d. -f1 | awk '{print }' | xargs kill 2> /dev/null
  ps -eo pid,command | grep infraredSensorAgent | grep -v grep | awk '{system("sudo kill -9 " $1)}'
    echo "Chariot Infrared Sensor agent stopped."
else
  echo "Chariot Infrared Sensor agent isn't running."
fi
