#!/bin/bash

if screen -list | grep -q "storageTrayAgent"; then
  screen -ls | grep -E "storageTrayAgent" | cut -d. -f1 | awk '{print }' | xargs kill 2> /dev/null
  ps -eo pid,command | grep storageTrayAgent | grep -v grep | awk '{system("sudo kill -9 " $1)}'
    echo "Chariot Storage Tray agent stopped."
else
  echo "Chariot Storage Tray agent isn't running."
fi
